# Generated by Django 4.2.8 on 2023-12-21 11:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBelenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Belenco Katalog',
                'verbose_name_plural': 'Belenco Katalog ',
            },
        ),
        migrations.AlterModelOptions(
            name='cataloggranite',
            options={'verbose_name': 'Granit Katalog', 'verbose_name_plural': 'Granit Katalog '},
        ),
    ]
