# Generated by Django 4.2.8 on 2023-12-21 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogbelenco_alter_cataloggranite_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCimstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Cimstone Katalog',
                'verbose_name_plural': 'Cimstone Katalog ',
            },
        ),
    ]
