# Generated by Django 4.2.8 on 2023-12-21 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_cataloggranitekitchen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMarble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Mermer Mutfak Tezgahi Katalog',
                'verbose_name_plural': 'Mermer Mutfak Tezgahi Katalog',
            },
        ),
        migrations.AlterModelOptions(
            name='cataloggranite',
            options={'verbose_name': 'Granit Doseme Katalog', 'verbose_name_plural': 'Granit Doseme Katalog '},
        ),
        migrations.AlterModelOptions(
            name='cataloggranitekitchen',
            options={'verbose_name': 'Granit Mutfak Tezgahi Katalog', 'verbose_name_plural': 'Granit Mutfak Tezgahi Katalog'},
        ),
    ]
