# Generated by Django 4.2.8 on 2023-12-22 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogmarble_alter_cataloggranite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Soru-Cevap',
                'verbose_name_plural': 'Sikça Sorulan Sorular',
            },
        ),
    ]
