# Generated by Django 4.2.8 on 2023-12-27 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Bize Ulaşin',
                'verbose_name_plural': 'Bize Ulaşin Yazisi',
            },
        ),
    ]
