# Generated by Django 4.2.8 on 2023-12-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_producttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
