# Generated by Django 4.2.8 on 2023-12-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
