# Generated by Django 4.2.8 on 2023-12-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_remove_category_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Döşeme',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Tezgahlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Tezgah Çeşitleri'},
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urunler.catfloor')),
            ],
            options={
                'verbose_name_plural': 'Tezgah Çeşitleri',
            },
        ),
    ]
