# Generated by Django 4.2.8 on 2023-12-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_catfloor_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name_plural': 'Doseme Çeşitleri'},
        ),
    ]
