# Generated by Django 4.2.9 on 2024-02-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_alter_floor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catfloor',
            options={'verbose_name_plural': 'Döşeme Çeşitleri'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name_plural': 'Dosemeler'},
        ),
    ]
