# Generated by Django 4.2.6 on 2024-01-29 08:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_alter_catfloor_options_alter_floor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Soru-Cevap',
                'verbose_name_plural': 'Sikça Sorulan Sorular',
            },
        ),
    ]
