# Generated by Django 4.2.9 on 2024-02-16 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Hakkimizda',
                'verbose_name_plural': 'Hakkimizda Yazisi',
            },
        ),
        migrations.CreateModel(
            name='Communicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('hour', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True)),
                ('x_link', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'sosyal medya hesabı',
                'verbose_name_plural': 'Sosyal Medya Hesapları',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Soru-Cevap',
                'verbose_name_plural': 'Sikça Sorulan Sorular',
            },
        ),
        migrations.CreateModel(
            name='FreeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Fiyat Teklifi',
                'verbose_name_plural': 'Fiyat Teklifi Yazisi',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Firma Logosu',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('project_title', models.CharField(blank=True, max_length=50, null=True)),
                ('project_choices', models.CharField(blank=True, choices=[('General', 'General Carpentry'), ('Custom', 'Custom Carpentry')], default='General', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'iş',
                'verbose_name_plural': 'Servisler',
            },
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('h5_text', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
                ('h1_text', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
                ('p_text', ckeditor.fields.RichTextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'site sileder',
                'verbose_name_plural': 'Site Slider Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('says', models.CharField(blank=True, max_length=500, null=True)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('jobs', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'referans',
                'verbose_name_plural': 'Referanslar',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Neden Biz',
                'verbose_name_plural': 'Neden Biz Yazisi',
            },
        ),
    ]
